export { default as Layout } from './Layout'
export { default as AccordionSidebar} from './nav/accordionSidebar'
export { default as Hero} from './hero'
export { default as Popular} from './popular.jsx'
export { default as PosterBox} from './posterBox'
export { default as PosterBoxMobile} from './posterBoxMobile'
export { default as PosterBoxSearch} from './posterBoxSearch'
export { default as Latest} from './latest'
export { default as WatchProviders} from './watchPoviders'
export { default as WatchListBox} from './watchListBox'
export {default as ErrorBoundary} from  './ErrorBoundary'